#!/usr/bin/env node
import fs from "fs";
import Bundler from "@irys/sdk";

// load Arweave wallet
const wallet = JSON.parse(
  fs.readFileSync(process.env.WALLET, 'utf-8')
);

const main = async () => {
  const token = "arweave";
  const bundler = new Bundler({
    url: "https://turbo.ardrive.io", // URL of the node you want to connect to, https://turbo.ardrive.io will facilitate upload using ArDrive Turbo.
    token, // Token used for payment and signing
    key: wallet, // Arweave wallet
  });

  const receipt = await bundler.uploadFile("AOS.wasm", {
    tags: [
      { name: 'Content-Type', value: 'application/wasm' },
      { name: 'Data-Protocol', value: 'ao' },
      { name: 'Type', value: 'Module' },
      { name: 'Variant', value: 'ao.TN.1' },
      { name: 'Module-Format', value: 'wasm64-unknown-emscripten-draft_2024_02_15' },
      { name: 'Input-Encoding', value: 'JSON-1' },
      { name: 'Output-Encoding', value: 'JSON-1' },
      { name: 'Memory-Limit', value: '15-gb' },
      { name: 'Compute-Limit', value: '9000000000000' },
    ]
  });
  console.log(receipt);
  console.log('ModuleID: ', receipt.id)
}

main()